-- 🦾 Robotic Gripper Database Setup Script
-- Run this in your Supabase SQL Editor

-- 1. Create the telemetry table for sensor data
CREATE TABLE telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  fsr_value INTEGER,
  motor_current FLOAT4,
  temperature FLOAT4,
  humidity FLOAT4,
  battery_pct INTEGER
);

-- 2. Create the commands table for gripper control
CREATE TABLE commands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  type TEXT NOT NULL, -- 'GRIP', 'RELEASE', 'RESET'
  value TEXT,
  status TEXT DEFAULT 'PENDING' -- 'PENDING', 'EXECUTED'
);

-- 3. Enable Realtime for both tables
ALTER PUBLICATION supabase_realtime ADD TABLE telemetry;
ALTER PUBLICATION supabase_realtime ADD TABLE commands;

-- 4. Disable RLS for easy testing (Enable later for security)
ALTER TABLE telemetry DISABLE ROW LEVEL SECURITY;
ALTER TABLE commands DISABLE ROW LEVEL SECURITY;
